//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.17 at 11:12:08 PM CEST 
//


package org.rub.nds.elearning.sso.saml.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for samlTokenProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samlTokenProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseHeaderDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}responseHeaderDecoratorType"/>
 *         &lt;element name="assertionHeaderDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}assertionHeaderDecoratorType"/>
 *         &lt;element name="assertionConditionsDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}assertionConditionsDecoratorType"/>
 *         &lt;element name="assertionSubjectDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}assertionSubjectDecoratorType"/>
 *         &lt;element name="assertionAuthnStatementDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}assertionAuthnStatementDecoratorType"/>
 *         &lt;element name="tokenSignatureDecorator" type="{http://www.api.saml.sso.elearning.nds.rub.org}tokenSignatureDecoratorType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samlTokenProfileType", propOrder = {
    "responseHeaderDecorator",
    "assertionHeaderDecorator",
    "assertionConditionsDecorator",
    "assertionSubjectDecorator",
    "assertionAuthnStatementDecorator",
    "tokenSignatureDecorator"
})
public class SamlTokenProfileType {

    @XmlElement(required = true)
    protected ResponseHeaderDecoratorType responseHeaderDecorator;
    @XmlElement(required = true)
    protected AssertionHeaderDecoratorType assertionHeaderDecorator;
    @XmlElement(required = true)
    protected AssertionConditionsDecoratorType assertionConditionsDecorator;
    @XmlElement(required = true)
    protected AssertionSubjectDecoratorType assertionSubjectDecorator;
    @XmlElement(required = true)
    protected AssertionAuthnStatementDecoratorType assertionAuthnStatementDecorator;
    @XmlElement(required = true)
    protected TokenSignatureDecoratorType tokenSignatureDecorator;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the responseHeaderDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseHeaderDecoratorType }
     *     
     */
    public ResponseHeaderDecoratorType getResponseHeaderDecorator() {
        return responseHeaderDecorator;
    }

    /**
     * Sets the value of the responseHeaderDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseHeaderDecoratorType }
     *     
     */
    public void setResponseHeaderDecorator(ResponseHeaderDecoratorType value) {
        this.responseHeaderDecorator = value;
    }

    /**
     * Gets the value of the assertionHeaderDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link AssertionHeaderDecoratorType }
     *     
     */
    public AssertionHeaderDecoratorType getAssertionHeaderDecorator() {
        return assertionHeaderDecorator;
    }

    /**
     * Sets the value of the assertionHeaderDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertionHeaderDecoratorType }
     *     
     */
    public void setAssertionHeaderDecorator(AssertionHeaderDecoratorType value) {
        this.assertionHeaderDecorator = value;
    }

    /**
     * Gets the value of the assertionConditionsDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link AssertionConditionsDecoratorType }
     *     
     */
    public AssertionConditionsDecoratorType getAssertionConditionsDecorator() {
        return assertionConditionsDecorator;
    }

    /**
     * Sets the value of the assertionConditionsDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertionConditionsDecoratorType }
     *     
     */
    public void setAssertionConditionsDecorator(AssertionConditionsDecoratorType value) {
        this.assertionConditionsDecorator = value;
    }

    /**
     * Gets the value of the assertionSubjectDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link AssertionSubjectDecoratorType }
     *     
     */
    public AssertionSubjectDecoratorType getAssertionSubjectDecorator() {
        return assertionSubjectDecorator;
    }

    /**
     * Sets the value of the assertionSubjectDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertionSubjectDecoratorType }
     *     
     */
    public void setAssertionSubjectDecorator(AssertionSubjectDecoratorType value) {
        this.assertionSubjectDecorator = value;
    }

    /**
     * Gets the value of the assertionAuthnStatementDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link AssertionAuthnStatementDecoratorType }
     *     
     */
    public AssertionAuthnStatementDecoratorType getAssertionAuthnStatementDecorator() {
        return assertionAuthnStatementDecorator;
    }

    /**
     * Sets the value of the assertionAuthnStatementDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertionAuthnStatementDecoratorType }
     *     
     */
    public void setAssertionAuthnStatementDecorator(AssertionAuthnStatementDecoratorType value) {
        this.assertionAuthnStatementDecorator = value;
    }

    /**
     * Gets the value of the tokenSignatureDecorator property.
     * 
     * @return
     *     possible object is
     *     {@link TokenSignatureDecoratorType }
     *     
     */
    public TokenSignatureDecoratorType getTokenSignatureDecorator() {
        return tokenSignatureDecorator;
    }

    /**
     * Sets the value of the tokenSignatureDecorator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenSignatureDecoratorType }
     *     
     */
    public void setTokenSignatureDecorator(TokenSignatureDecoratorType value) {
        this.tokenSignatureDecorator = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
