//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.17 at 11:12:08 PM CEST 
//


package org.rub.nds.elearning.sso.saml.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rub.nds.elearning.sso.saml.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SAMLProfileStorage_QNAME = new QName("http://www.api.saml.sso.elearning.nds.rub.org", "SAMLProfileStorage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rub.nds.elearning.sso.saml.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SAMLProfileStorageType }
     * 
     */
    public SAMLProfileStorageType createSAMLProfileStorageType() {
        return new SAMLProfileStorageType();
    }

    /**
     * Create an instance of {@link TokenSignatureDecoratorType }
     * 
     */
    public TokenSignatureDecoratorType createTokenSignatureDecoratorType() {
        return new TokenSignatureDecoratorType();
    }

    /**
     * Create an instance of {@link SamlTokenProfileType }
     * 
     */
    public SamlTokenProfileType createSamlTokenProfileType() {
        return new SamlTokenProfileType();
    }

    /**
     * Create an instance of {@link AssertionSubjectDecoratorType }
     * 
     */
    public AssertionSubjectDecoratorType createAssertionSubjectDecoratorType() {
        return new AssertionSubjectDecoratorType();
    }

    /**
     * Create an instance of {@link SamlTokenProfilesType }
     * 
     */
    public SamlTokenProfilesType createSamlTokenProfilesType() {
        return new SamlTokenProfilesType();
    }

    /**
     * Create an instance of {@link SamlRequestProfileType }
     * 
     */
    public SamlRequestProfileType createSamlRequestProfileType() {
        return new SamlRequestProfileType();
    }

    /**
     * Create an instance of {@link AudienceRestrictionsType }
     * 
     */
    public AudienceRestrictionsType createAudienceRestrictionsType() {
        return new AudienceRestrictionsType();
    }

    /**
     * Create an instance of {@link RegisteredIdPsType }
     * 
     */
    public RegisteredIdPsType createRegisteredIdPsType() {
        return new RegisteredIdPsType();
    }

    /**
     * Create an instance of {@link RegisteredSPsType }
     * 
     */
    public RegisteredSPsType createRegisteredSPsType() {
        return new RegisteredSPsType();
    }

    /**
     * Create an instance of {@link AssertionConditionsDecoratorType }
     * 
     */
    public AssertionConditionsDecoratorType createAssertionConditionsDecoratorType() {
        return new AssertionConditionsDecoratorType();
    }

    /**
     * Create an instance of {@link AssertionAuthnStatementDecoratorType }
     * 
     */
    public AssertionAuthnStatementDecoratorType createAssertionAuthnStatementDecoratorType() {
        return new AssertionAuthnStatementDecoratorType();
    }

    /**
     * Create an instance of {@link RegisteredSPType }
     * 
     */
    public RegisteredSPType createRegisteredSPType() {
        return new RegisteredSPType();
    }

    /**
     * Create an instance of {@link AssertionHeaderDecoratorType }
     * 
     */
    public AssertionHeaderDecoratorType createAssertionHeaderDecoratorType() {
        return new AssertionHeaderDecoratorType();
    }

    /**
     * Create an instance of {@link SamlVerificationProfilesType }
     * 
     */
    public SamlVerificationProfilesType createSamlVerificationProfilesType() {
        return new SamlVerificationProfilesType();
    }

    /**
     * Create an instance of {@link ResponseHeaderDecoratorType }
     * 
     */
    public ResponseHeaderDecoratorType createResponseHeaderDecoratorType() {
        return new ResponseHeaderDecoratorType();
    }

    /**
     * Create an instance of {@link RegisteredIdPType }
     * 
     */
    public RegisteredIdPType createRegisteredIdPType() {
        return new RegisteredIdPType();
    }

    /**
     * Create an instance of {@link SamlRequestProfilesType }
     * 
     */
    public SamlRequestProfilesType createSamlRequestProfilesType() {
        return new SamlRequestProfilesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAMLProfileStorageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.api.saml.sso.elearning.nds.rub.org", name = "SAMLProfileStorage")
    public JAXBElement<SAMLProfileStorageType> createSAMLProfileStorage(SAMLProfileStorageType value) {
        return new JAXBElement<SAMLProfileStorageType>(_SAMLProfileStorage_QNAME, SAMLProfileStorageType.class, null, value);
    }

}
