//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.17 at 11:12:08 PM CEST 
//


package org.rub.nds.elearning.sso.saml.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SAMLProfileStorageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAMLProfileStorageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registeredSPs" type="{http://www.api.saml.sso.elearning.nds.rub.org}registeredSPsType" minOccurs="0"/>
 *         &lt;element name="samlTokenProfiles" type="{http://www.api.saml.sso.elearning.nds.rub.org}samlTokenProfilesType" minOccurs="0"/>
 *         &lt;element name="samlRequestProfiles" type="{http://www.api.saml.sso.elearning.nds.rub.org}samlRequestProfilesType" minOccurs="0"/>
 *         &lt;element name="samlVerificationProfiles" type="{http://www.api.saml.sso.elearning.nds.rub.org}samlVerificationProfilesType" minOccurs="0"/>
 *         &lt;element name="registeredIdPs" type="{http://www.api.saml.sso.elearning.nds.rub.org}registeredIdPsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAMLProfileStorageType", propOrder = {
    "registeredSPs",
    "samlTokenProfiles",
    "samlRequestProfiles",
    "samlVerificationProfiles",
    "registeredIdPs"
})
public class SAMLProfileStorageType {

    protected RegisteredSPsType registeredSPs;
    protected SamlTokenProfilesType samlTokenProfiles;
    protected SamlRequestProfilesType samlRequestProfiles;
    protected SamlVerificationProfilesType samlVerificationProfiles;
    protected RegisteredIdPsType registeredIdPs;

    /**
     * Gets the value of the registeredSPs property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredSPsType }
     *     
     */
    public RegisteredSPsType getRegisteredSPs() {
        return registeredSPs;
    }

    /**
     * Sets the value of the registeredSPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredSPsType }
     *     
     */
    public void setRegisteredSPs(RegisteredSPsType value) {
        this.registeredSPs = value;
    }

    /**
     * Gets the value of the samlTokenProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link SamlTokenProfilesType }
     *     
     */
    public SamlTokenProfilesType getSamlTokenProfiles() {
        return samlTokenProfiles;
    }

    /**
     * Sets the value of the samlTokenProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlTokenProfilesType }
     *     
     */
    public void setSamlTokenProfiles(SamlTokenProfilesType value) {
        this.samlTokenProfiles = value;
    }

    /**
     * Gets the value of the samlRequestProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link SamlRequestProfilesType }
     *     
     */
    public SamlRequestProfilesType getSamlRequestProfiles() {
        return samlRequestProfiles;
    }

    /**
     * Sets the value of the samlRequestProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlRequestProfilesType }
     *     
     */
    public void setSamlRequestProfiles(SamlRequestProfilesType value) {
        this.samlRequestProfiles = value;
    }

    /**
     * Gets the value of the samlVerificationProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link SamlVerificationProfilesType }
     *     
     */
    public SamlVerificationProfilesType getSamlVerificationProfiles() {
        return samlVerificationProfiles;
    }

    /**
     * Sets the value of the samlVerificationProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlVerificationProfilesType }
     *     
     */
    public void setSamlVerificationProfiles(SamlVerificationProfilesType value) {
        this.samlVerificationProfiles = value;
    }

    /**
     * Gets the value of the registeredIdPs property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredIdPsType }
     *     
     */
    public RegisteredIdPsType getRegisteredIdPs() {
        return registeredIdPs;
    }

    /**
     * Sets the value of the registeredIdPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredIdPsType }
     *     
     */
    public void setRegisteredIdPs(RegisteredIdPsType value) {
        this.registeredIdPs = value;
    }

}
