//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//


package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assertionSubjectDecoratorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assertionSubjectDecoratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameIDValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameIDformat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameIDnameQualifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameIDsPNameQualifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameIDsPProvidedID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sbjConfirmMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sbjConfirmationDataAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sbjConfirmationDataRecipient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timestampDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assertionSubjectDecoratorType", propOrder = {
    "nameIDValue",
    "nameIDformat",
    "nameIDnameQualifier",
    "nameIDsPNameQualifier",
    "nameIDsPProvidedID",
    "sbjConfirmMethod",
    "sbjConfirmationDataAddress",
    "sbjConfirmationDataRecipient",
    "timestampDuration"
})
public class AssertionSubjectDecoratorType {

    protected String nameIDValue;
    protected String nameIDformat;
    protected String nameIDnameQualifier;
    protected String nameIDsPNameQualifier;
    protected String nameIDsPProvidedID;
    protected String sbjConfirmMethod;
    protected String sbjConfirmationDataAddress;
    protected String sbjConfirmationDataRecipient;
    protected Integer timestampDuration;

    /**
     * Gets the value of the nameIDValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameIDValue() {
        return nameIDValue;
    }

    /**
     * Sets the value of the nameIDValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameIDValue(String value) {
        this.nameIDValue = value;
    }

    /**
     * Gets the value of the nameIDformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameIDformat() {
        return nameIDformat;
    }

    /**
     * Sets the value of the nameIDformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameIDformat(String value) {
        this.nameIDformat = value;
    }

    /**
     * Gets the value of the nameIDnameQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameIDnameQualifier() {
        return nameIDnameQualifier;
    }

    /**
     * Sets the value of the nameIDnameQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameIDnameQualifier(String value) {
        this.nameIDnameQualifier = value;
    }

    /**
     * Gets the value of the nameIDsPNameQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameIDsPNameQualifier() {
        return nameIDsPNameQualifier;
    }

    /**
     * Sets the value of the nameIDsPNameQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameIDsPNameQualifier(String value) {
        this.nameIDsPNameQualifier = value;
    }

    /**
     * Gets the value of the nameIDsPProvidedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameIDsPProvidedID() {
        return nameIDsPProvidedID;
    }

    /**
     * Sets the value of the nameIDsPProvidedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameIDsPProvidedID(String value) {
        this.nameIDsPProvidedID = value;
    }

    /**
     * Gets the value of the sbjConfirmMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbjConfirmMethod() {
        return sbjConfirmMethod;
    }

    /**
     * Sets the value of the sbjConfirmMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbjConfirmMethod(String value) {
        this.sbjConfirmMethod = value;
    }

    /**
     * Gets the value of the sbjConfirmationDataAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbjConfirmationDataAddress() {
        return sbjConfirmationDataAddress;
    }

    /**
     * Sets the value of the sbjConfirmationDataAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbjConfirmationDataAddress(String value) {
        this.sbjConfirmationDataAddress = value;
    }

    /**
     * Gets the value of the sbjConfirmationDataRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbjConfirmationDataRecipient() {
        return sbjConfirmationDataRecipient;
    }

    /**
     * Sets the value of the sbjConfirmationDataRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbjConfirmationDataRecipient(String value) {
        this.sbjConfirmationDataRecipient = value;
    }

    /**
     * Gets the value of the timestampDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimestampDuration() {
        return timestampDuration;
    }

    /**
     * Sets the value of the timestampDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimestampDuration(Integer value) {
        this.timestampDuration = value;
    }

}
