//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//

package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for assertionHeaderDecoratorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="assertionHeaderDecoratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issuerStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assertionHeaderDecoratorType", propOrder = { "issuerStr" })
public class AssertionHeaderDecoratorType {

    @XmlElement(required = true)
    protected String issuerStr;

    /**
     * Gets the value of the issuerStr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuerStr() {
        return issuerStr;
    }

    /**
     * Sets the value of the issuerStr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuerStr(String value) {
        this.issuerStr = value;
    }

}
