//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//

package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for assertionAuthnStatementDecoratorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="assertionAuthnStatementDecoratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timestamps" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sbjLocalityAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sbjLocalityDNS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authnContextDeclStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authnContextClassRefStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authnContextDeclRefStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assertionAuthnStatementDecoratorType", propOrder = { "timestamps", "sbjLocalityAddress",
        "sbjLocalityDNS", "authnContextDeclStr", "authnContextClassRefStr", "authnContextDeclRefStr" })
public class AssertionAuthnStatementDecoratorType {

    protected Integer timestamps;
    protected String sbjLocalityAddress;
    protected String sbjLocalityDNS;
    protected String authnContextDeclStr;
    protected String authnContextClassRefStr;
    protected String authnContextDeclRefStr;

    /**
     * Gets the value of the timestamps property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getTimestamps() {
        return timestamps;
    }

    /**
     * Sets the value of the timestamps property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setTimestamps(Integer value) {
        this.timestamps = value;
    }

    /**
     * Gets the value of the sbjLocalityAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSbjLocalityAddress() {
        return sbjLocalityAddress;
    }

    /**
     * Sets the value of the sbjLocalityAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSbjLocalityAddress(String value) {
        this.sbjLocalityAddress = value;
    }

    /**
     * Gets the value of the sbjLocalityDNS property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSbjLocalityDNS() {
        return sbjLocalityDNS;
    }

    /**
     * Sets the value of the sbjLocalityDNS property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSbjLocalityDNS(String value) {
        this.sbjLocalityDNS = value;
    }

    /**
     * Gets the value of the authnContextDeclStr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthnContextDeclStr() {
        return authnContextDeclStr;
    }

    /**
     * Sets the value of the authnContextDeclStr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAuthnContextDeclStr(String value) {
        this.authnContextDeclStr = value;
    }

    /**
     * Gets the value of the authnContextClassRefStr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthnContextClassRefStr() {
        return authnContextClassRefStr;
    }

    /**
     * Sets the value of the authnContextClassRefStr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAuthnContextClassRefStr(String value) {
        this.authnContextClassRefStr = value;
    }

    /**
     * Gets the value of the authnContextDeclRefStr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthnContextDeclRefStr() {
        return authnContextDeclRefStr;
    }

    /**
     * Sets the value of the authnContextDeclRefStr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAuthnContextDeclRefStr(String value) {
        this.authnContextDeclRefStr = value;
    }

}
