//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//


package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseHeaderDecoratorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseHeaderDecoratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issuerStr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusCodeURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addInResponseTo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="addDestination" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseHeaderDecoratorType", propOrder = {
    "issuerStr",
    "statusCodeURI",
    "addInResponseTo",
    "addDestination"
})
public class ResponseHeaderDecoratorType {

    @XmlElement(required = true)
    protected String issuerStr;
    protected String statusCodeURI;
    protected Boolean addInResponseTo;
    protected Boolean addDestination;

    /**
     * Gets the value of the issuerStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerStr() {
        return issuerStr;
    }

    /**
     * Sets the value of the issuerStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerStr(String value) {
        this.issuerStr = value;
    }

    /**
     * Gets the value of the statusCodeURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCodeURI() {
        return statusCodeURI;
    }

    /**
     * Sets the value of the statusCodeURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCodeURI(String value) {
        this.statusCodeURI = value;
    }

    /**
     * Gets the value of the addInResponseTo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddInResponseTo() {
        return addInResponseTo;
    }

    /**
     * Sets the value of the addInResponseTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddInResponseTo(Boolean value) {
        this.addInResponseTo = value;
    }

    /**
     * Gets the value of the addDestination property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddDestination() {
        return addDestination;
    }

    /**
     * Sets the value of the addDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddDestination(Boolean value) {
        this.addDestination = value;
    }

}
