//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//

package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for samlTokenVerificationChecksType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="samlTokenVerificationChecksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="verifySchema" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyXSW" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLResponseID" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLResponseIssueInstant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLResponseSignatureTrusted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLResponseSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLResponseInResponseTo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionID" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionSignatureTrusted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionInResponseTo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionIssueInstant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionSbjConfirmationTimestamps" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionSbjConfirmationDestination" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionSbjInResponseTo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionConditionsTimestamps" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionConditionsAudience" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifySAMLAssertionAuthnMethod" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyHolderOfKey" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samlTokenVerificationChecksType", propOrder = { "verifySchema", "verifyXSW", "verifySAMLResponseID",
        "verifySAMLResponseIssueInstant", "verifySAMLResponseSignatureTrusted", "verifySAMLResponseSignature",
        "verifySAMLResponseInResponseTo", "verifySAMLAssertionID", "verifySAMLAssertionSignatureTrusted",
        "verifySAMLAssertionSignature", "verifySAMLAssertionInResponseTo", "verifySAMLAssertionIssueInstant",
        "verifySAMLAssertionSbjConfirmationTimestamps", "verifySAMLAssertionSbjConfirmationDestination",
        "verifySAMLAssertionSbjInResponseTo", "verifySAMLAssertionConditionsTimestamps",
        "verifySAMLAssertionConditionsAudience", "verifySAMLAssertionAuthnMethod", "verifyHolderOfKey" })
public class SamlTokenVerificationChecksType {

    protected Boolean verifySchema;
    protected Boolean verifyXSW;
    protected Boolean verifySAMLResponseID;
    protected Boolean verifySAMLResponseIssueInstant;
    protected Boolean verifySAMLResponseSignatureTrusted;
    protected Boolean verifySAMLResponseSignature;
    protected Boolean verifySAMLResponseInResponseTo;
    protected Boolean verifySAMLAssertionID;
    protected Boolean verifySAMLAssertionSignatureTrusted;
    protected Boolean verifySAMLAssertionSignature;
    protected Boolean verifySAMLAssertionInResponseTo;
    protected Boolean verifySAMLAssertionIssueInstant;
    protected Boolean verifySAMLAssertionSbjConfirmationTimestamps;
    protected Boolean verifySAMLAssertionSbjConfirmationDestination;
    protected Boolean verifySAMLAssertionSbjInResponseTo;
    protected Boolean verifySAMLAssertionConditionsTimestamps;
    protected Boolean verifySAMLAssertionConditionsAudience;
    protected Boolean verifySAMLAssertionAuthnMethod;
    protected Boolean verifyHolderOfKey;

    /**
     * Gets the value of the verifySchema property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySchema() {
        return verifySchema;
    }

    /**
     * Sets the value of the verifySchema property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySchema(Boolean value) {
        this.verifySchema = value;
    }

    /**
     * Gets the value of the verifyXSW property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifyXSW() {
        return verifyXSW;
    }

    /**
     * Sets the value of the verifyXSW property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifyXSW(Boolean value) {
        this.verifyXSW = value;
    }

    /**
     * Gets the value of the verifySAMLResponseID property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLResponseID() {
        return verifySAMLResponseID;
    }

    /**
     * Sets the value of the verifySAMLResponseID property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLResponseID(Boolean value) {
        this.verifySAMLResponseID = value;
    }

    /**
     * Gets the value of the verifySAMLResponseIssueInstant property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLResponseIssueInstant() {
        return verifySAMLResponseIssueInstant;
    }

    /**
     * Sets the value of the verifySAMLResponseIssueInstant property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLResponseIssueInstant(Boolean value) {
        this.verifySAMLResponseIssueInstant = value;
    }

    /**
     * Gets the value of the verifySAMLResponseSignatureTrusted property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLResponseSignatureTrusted() {
        return verifySAMLResponseSignatureTrusted;
    }

    /**
     * Sets the value of the verifySAMLResponseSignatureTrusted property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLResponseSignatureTrusted(Boolean value) {
        this.verifySAMLResponseSignatureTrusted = value;
    }

    /**
     * Gets the value of the verifySAMLResponseSignature property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLResponseSignature() {
        return verifySAMLResponseSignature;
    }

    /**
     * Sets the value of the verifySAMLResponseSignature property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLResponseSignature(Boolean value) {
        this.verifySAMLResponseSignature = value;
    }

    /**
     * Gets the value of the verifySAMLResponseInResponseTo property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLResponseInResponseTo() {
        return verifySAMLResponseInResponseTo;
    }

    /**
     * Sets the value of the verifySAMLResponseInResponseTo property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLResponseInResponseTo(Boolean value) {
        this.verifySAMLResponseInResponseTo = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionID property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionID() {
        return verifySAMLAssertionID;
    }

    /**
     * Sets the value of the verifySAMLAssertionID property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionID(Boolean value) {
        this.verifySAMLAssertionID = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionSignatureTrusted property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionSignatureTrusted() {
        return verifySAMLAssertionSignatureTrusted;
    }

    /**
     * Sets the value of the verifySAMLAssertionSignatureTrusted property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionSignatureTrusted(Boolean value) {
        this.verifySAMLAssertionSignatureTrusted = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionSignature property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionSignature() {
        return verifySAMLAssertionSignature;
    }

    /**
     * Sets the value of the verifySAMLAssertionSignature property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionSignature(Boolean value) {
        this.verifySAMLAssertionSignature = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionInResponseTo property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionInResponseTo() {
        return verifySAMLAssertionInResponseTo;
    }

    /**
     * Sets the value of the verifySAMLAssertionInResponseTo property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionInResponseTo(Boolean value) {
        this.verifySAMLAssertionInResponseTo = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionIssueInstant property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionIssueInstant() {
        return verifySAMLAssertionIssueInstant;
    }

    /**
     * Sets the value of the verifySAMLAssertionIssueInstant property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionIssueInstant(Boolean value) {
        this.verifySAMLAssertionIssueInstant = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionSbjConfirmationTimestamps
     * property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionSbjConfirmationTimestamps() {
        return verifySAMLAssertionSbjConfirmationTimestamps;
    }

    /**
     * Sets the value of the verifySAMLAssertionSbjConfirmationTimestamps
     * property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionSbjConfirmationTimestamps(Boolean value) {
        this.verifySAMLAssertionSbjConfirmationTimestamps = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionSbjConfirmationDestination
     * property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionSbjConfirmationDestination() {
        return verifySAMLAssertionSbjConfirmationDestination;
    }

    /**
     * Sets the value of the verifySAMLAssertionSbjConfirmationDestination
     * property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionSbjConfirmationDestination(Boolean value) {
        this.verifySAMLAssertionSbjConfirmationDestination = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionSbjInResponseTo property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionSbjInResponseTo() {
        return verifySAMLAssertionSbjInResponseTo;
    }

    /**
     * Sets the value of the verifySAMLAssertionSbjInResponseTo property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionSbjInResponseTo(Boolean value) {
        this.verifySAMLAssertionSbjInResponseTo = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionConditionsTimestamps property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionConditionsTimestamps() {
        return verifySAMLAssertionConditionsTimestamps;
    }

    /**
     * Sets the value of the verifySAMLAssertionConditionsTimestamps property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionConditionsTimestamps(Boolean value) {
        this.verifySAMLAssertionConditionsTimestamps = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionConditionsAudience property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionConditionsAudience() {
        return verifySAMLAssertionConditionsAudience;
    }

    /**
     * Sets the value of the verifySAMLAssertionConditionsAudience property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionConditionsAudience(Boolean value) {
        this.verifySAMLAssertionConditionsAudience = value;
    }

    /**
     * Gets the value of the verifySAMLAssertionAuthnMethod property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifySAMLAssertionAuthnMethod() {
        return verifySAMLAssertionAuthnMethod;
    }

    /**
     * Sets the value of the verifySAMLAssertionAuthnMethod property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifySAMLAssertionAuthnMethod(Boolean value) {
        this.verifySAMLAssertionAuthnMethod = value;
    }

    /**
     * Gets the value of the verifyHolderOfKey property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isVerifyHolderOfKey() {
        return verifyHolderOfKey;
    }

    /**
     * Sets the value of the verifyHolderOfKey property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVerifyHolderOfKey(Boolean value) {
        this.verifyHolderOfKey = value;
    }

}
