//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.09 at 01:11:59 PM EET 
//

package org.rub.nds.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tokenSignatureDecoratorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tokenSignatureDecoratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signAssertion" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="signResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="signAuthnRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tokenSignatureDecoratorType", propOrder = { "signAssertion", "signResponse", "signAuthnRequest" })
public class TokenSignatureDecoratorType {

    protected Boolean signAssertion;
    protected Boolean signResponse;
    protected Boolean signAuthnRequest;

    /**
     * Gets the value of the signAssertion property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSignAssertion() {
        return signAssertion;
    }

    /**
     * Sets the value of the signAssertion property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSignAssertion(Boolean value) {
        this.signAssertion = value;
    }

    /**
     * Gets the value of the signResponse property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSignResponse() {
        return signResponse;
    }

    /**
     * Sets the value of the signResponse property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSignResponse(Boolean value) {
        this.signResponse = value;
    }

    /**
     * Gets the value of the signAuthnRequest property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isSignAuthnRequest() {
        return signAuthnRequest;
    }

    /**
     * Sets the value of the signAuthnRequest property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setSignAuthnRequest(Boolean value) {
        this.signAuthnRequest = value;
    }

}
